---
- name: "Play 1- cgi website configuration"  
  hosts: webservers
  become: yes
  tasks:
    - name: "install git"
      yum:
        name: "httpd"
        state: present
    - name: ensure a list of packages installed
      yum:
        name: "{{ packages }}"
      vars:
        packages:
          - httpd
          - httpd-tools
